import {
  User,
  Patient,
  Appointment,
  ConsultationNote,
  Prescription,
  LabTest,
  Message,
  BillingRecord,
} from "@/types";

// Mock doctors and receptionists
export const MOCK_DOCTORS: User[] = [
  {
    id: "2",
    name: "Dr. Michael Chen",
    email: "doctor@hospital.com",
    role: "doctor",
    specialization: "General Practice",
    department: "Internal Medicine",
  },
  {
    id: "3",
    name: "Dr. Sarah Williams",
    email: "sarah.williams@hospital.com",
    role: "doctor",
    specialization: "Cardiology",
    department: "Cardiology",
  },
  {
    id: "4",
    name: "Dr. James Brown",
    email: "james.brown@hospital.com",
    role: "doctor",
    specialization: "Pediatrics",
    department: "Pediatrics",
  },
];

export const MOCK_RECEPTIONISTS: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "receptionist@hospital.com",
    role: "receptionist",
    department: "Front Desk",
  },
  {
    id: "5",
    name: "Emma Davis",
    email: "emma.davis@hospital.com",
    role: "receptionist",
    department: "Front Desk",
  },
];

export const MOCK_USERS: User[] = [...MOCK_DOCTORS, ...MOCK_RECEPTIONISTS];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@email.com",
    phone: "+1-555-0123",
    dateOfBirth: "1985-03-15",
    address: "123 Main St, Anytown, AT 12345",
    medicalHistory: ["Hypertension", "Type 2 Diabetes"],
    emergencyContact: {
      name: "Jane Doe",
      phone: "+1-555-0124",
      relationship: "Spouse",
    },
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-07-20T14:30:00Z",
  },
  {
    id: "2",
    firstName: "Emily",
    lastName: "Smith",
    email: "emily.smith@email.com",
    phone: "+1-555-0125",
    dateOfBirth: "1992-08-22",
    address: "456 Oak Ave, Somewhere, SW 67890",
    medicalHistory: ["Asthma", "Allergies"],
    emergencyContact: {
      name: "Robert Smith",
      phone: "+1-555-0126",
      relationship: "Father",
    },
    createdAt: "2024-02-10T09:15:00Z",
    updatedAt: "2024-07-21T11:45:00Z",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@email.com",
    phone: "+1-555-0127",
    dateOfBirth: "1978-12-03",
    address: "789 Pine Rd, Elsewhere, EW 54321",
    medicalHistory: ["High Cholesterol"],
    emergencyContact: {
      name: "Lisa Johnson",
      phone: "+1-555-0128",
      relationship: "Wife",
    },
    createdAt: "2024-03-05T16:20:00Z",
    updatedAt: "2024-07-19T13:10:00Z",
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "John Doe",
    doctorId: "2",
    date: "2026-02-04",
    time: "09:00",
    type: "consultation",
    status: "pending",
    visitReason: "Annual checkup and blood pressure monitoring",
    notes: "Patient requested morning appointment",
    createdAt: "2026-02-01T14:00:00Z",
    updatedAt: "2026-02-01T14:00:00Z",
    createdBy: "1",
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Emily Smith",
    doctorId: "2",
    date: "2026-02-04",
    time: "10:30",
    type: "follow-up",
    status: "confirmed",
    visitReason: "Asthma follow-up and prescription renewal",
    notes: "Bring previous prescription",
    createdAt: "2026-01-28T10:30:00Z",
    updatedAt: "2026-02-03T09:00:00Z",
    createdBy: "1",
  },
  {
    id: "3",
    patientId: "3",
    patientName: "Michael Johnson",
    doctorId: "3",
    date: "2026-02-03",
    time: "14:00",
    type: "consultation",
    status: "completed",
    visitReason: "Cholesterol review and heart health assessment",
    notes: "Review lab test results",
    createdAt: "2026-01-25T09:00:00Z",
    updatedAt: "2026-02-03T15:30:00Z",
    createdBy: "1",
  },
  {
    id: "4",
    patientId: "1",
    patientName: "John Doe",
    doctorId: "2",
    date: "2026-02-04",
    time: "14:00",
    type: "consultation",
    status: "confirmed",
    visitReason: "Diabetes monitoring and medication adjustment",
    notes: "Fasting blood sugar test required",
    createdAt: "2026-01-30T11:00:00Z",
    updatedAt: "2026-02-02T15:30:00Z",
    createdBy: "1",
  },
  {
    id: "5",
    patientId: "2",
    patientName: "Emily Smith",
    doctorId: "4",
    date: "2026-02-05",
    time: "11:00",
    type: "consultation",
    status: "pending",
    visitReason: "Allergy consultation",
    notes: "Patient experiencing seasonal allergies",
    createdAt: "2026-02-03T16:00:00Z",
    updatedAt: "2026-02-03T16:00:00Z",
    createdBy: "5",
  },
  {
    id: "6",
    patientId: "3",
    patientName: "Michael Johnson",
    doctorId: "2",
    date: "2026-02-01",
    time: "10:00",
    type: "follow-up",
    status: "cancelled",
    visitReason: "Follow-up consultation",
    notes: "Patient cancelled due to work commitment",
    cancelReason: "Patient requested cancellation - rescheduled",
    createdAt: "2026-01-20T09:00:00Z",
    updatedAt: "2026-02-01T08:00:00Z",
    createdBy: "1",
  },
];

export const MOCK_CONSULTATION_NOTES: ConsultationNote[] = [
  {
    id: "1",
    appointmentId: "3",
    doctorId: "2",
    notes:
      "Patient reports feeling well. Blood pressure within normal range. Continue current medication.",
    diagnosis: "Hypertension - well controlled",
    treatment: "Continue Lisinopril 10mg daily",
    createdAt: "2024-07-21T14:45:00Z",
  },
];

export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: "1",
    patientId: "1",
    doctorId: "2",
    appointmentId: "3",
    medications: [
      {
        name: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "30 days",
        instructions: "Take with food",
      },
      {
        name: "Metformin",
        dosage: "500mg",
        frequency: "Twice daily",
        duration: "30 days",
        instructions: "Take with meals",
      },
    ],
    createdAt: "2024-07-21T14:50:00Z",
  },
];

export const MOCK_LAB_TESTS: LabTest[] = [
  {
    id: "1",
    patientId: "1",
    doctorId: "2",
    appointmentId: "1",
    testType: "Complete Blood Count",
    status: "requested",
    requestedAt: "2024-07-21T15:00:00Z",
  },
  {
    id: "2",
    patientId: "3",
    doctorId: "2",
    appointmentId: "3",
    testType: "Lipid Panel",
    status: "completed",
    results:
      "Total cholesterol: 180 mg/dL (Normal). LDL: 100 mg/dL (Borderline high).",
    requestedAt: "2024-07-20T14:00:00Z",
    completedAt: "2024-07-21T10:30:00Z",
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "1",
    senderId: "1",
    receiverId: "2",
    content: "Dr. Chen, patient John Doe has arrived early for his 9 AM appointment.",
    timestamp: "2026-02-04T08:45:00Z",
    read: true,
    readAt: "2026-02-04T08:46:00Z",
    appointmentId: "1",
    category: "appointment",
  },
  {
    id: "2",
    senderId: "2",
    receiverId: "1",
    content: "Thanks Sarah, I'll be ready in 5 minutes.",
    timestamp: "2026-02-04T08:47:00Z",
    read: true,
    readAt: "2026-02-04T08:47:30Z",
    appointmentId: "1",
    category: "appointment",
  },
  {
    id: "3",
    senderId: "1",
    receiverId: "2",
    content: "Emily Smith called - she's running 15 minutes late for her 10:30 appointment.",
    timestamp: "2026-02-04T10:10:00Z",
    read: false,
    appointmentId: "2",
    category: "urgent",
  },
  {
    id: "4",
    senderId: "2",
    receiverId: "1",
    content: "No problem, I can see the next patient first.",
    timestamp: "2026-02-04T10:12:00Z",
    read: true,
    readAt: "2026-02-04T10:13:00Z",
    appointmentId: "2",
    category: "appointment",
  },
  {
    id: "5",
    senderId: "3",
    receiverId: "1",
    content: "Room 3 will be available earlier today. Can we move some afternoon appointments?",
    timestamp: "2026-02-04T09:30:00Z",
    read: true,
    readAt: "2026-02-04T09:35:00Z",
    category: "general",
  },
  {
    id: "6",
    senderId: "1",
    receiverId: "3",
    content: "Yes, I can adjust the 2 PM appointments. I'll send you the updated schedule.",
    timestamp: "2026-02-04T09:40:00Z",
    read: true,
    readAt: "2026-02-04T09:41:00Z",
    category: "general",
  },
];

export const MOCK_BILLING_RECORDS: BillingRecord[] = [
  {
    id: "1",
    patientId: "1",
    appointmentId: "3",
    amount: 150.0,
    description: "Consultation - Diabetes follow-up",
    status: "paid",
    createdAt: "2024-07-21T15:00:00Z",
    paidAt: "2024-07-21T16:30:00Z",
  },
  {
    id: "2",
    patientId: "2",
    appointmentId: "2",
    amount: 125.0,
    description: "Consultation - Asthma follow-up",
    status: "pending",
    createdAt: "2024-07-22T10:30:00Z",
  },
  {
    id: "3",
    patientId: "3",
    appointmentId: "3",
    amount: 200.0,
    description: "Consultation + Lab Tests",
    status: "pending",
    createdAt: "2024-07-21T14:00:00Z",
  },
];
